groups:
  - name: group1
    reviewers: 1
    internal_reviewers: 1
    usernames:
      - elias-carlson
      - SimplemathicDev
      - krystynaziobro
      - cvazouras

  - name: group2
    reviewers: 1
    internal_reviewers: 1
    usernames:
      - erikwessman
      - theowiik
