groups:
  - name: devs
    reviewers: 2 # how many reviewers do you want to assign?
    internal_reviewers: 2 # how many reviewers do you want to assign when the PR author belongs to this group?
    usernames:
      - erikwessman
      - elias-carlson
      - SimplemathicDev
      - krystynaziobro
      - cvazouras
