groups:
  - name: devs
    reviewers: 1            # how many reviewers do you want to assign?
    internal_reviewers: 1   # how many reviewers do you want to assign when the PR author belongs to this group?
    usernames:
      - erikwessman
      - theowiik
      - elias-carlson
      - SimplemathicDev
      - krystynaziobro
      - cvazouras
